#!/bin/bash
# Point-in-time recovery (PITR) procedure.
#
# Restores the PostgreSQL cluster to a specific point in time using
# wal-g base backups + WAL archive replay.
#
# WARNING: This is a destructive operation. The existing database
# cluster will be replaced. Make sure you have a reason to do this.
#
# Prerequisites:
#   - PostgreSQL must be STOPPED before running this script
#   - wal-g configured with S3 access (same bucket as archiving)
#   - Target timestamp must be within the available WAL range
#
# Usage:
#   # Stop PostgreSQL first!
#   systemctl stop postgresql
#
#   # Restore to a specific point in time
#   ./restore.sh "2026-04-05 14:30:00+00"
#
#   # Restore to latest available (most recent WAL)
#   ./restore.sh latest
#
#   # Then start PostgreSQL
#   systemctl start postgresql

set -euo pipefail

TARGET="${1:-}"
PGDATA="${PGDATA:-/var/lib/postgresql/data}"

if [ -z "$TARGET" ]; then
    echo "Usage: $0 <target-timestamp|latest>"
    echo ""
    echo "Examples:"
    echo "  $0 '2026-04-05 14:30:00+00'    # Restore to specific time"
    echo "  $0 latest                        # Restore to latest WAL"
    echo ""
    echo "IMPORTANT: Stop PostgreSQL before running this script."
    exit 1
fi

# Load wal-g environment from envdir layout.
if [ -d /etc/wal-g/env ]; then
    for f in /etc/wal-g/env/*; do
        [ -f "$f" ] || continue
        export "$(basename "$f")=$(cat "$f")"
    done
fi

# ── Safety checks ──

if pg_isready &>/dev/null; then
    echo "ERROR: PostgreSQL is still running. Stop it first:"
    echo "  systemctl stop postgresql"
    echo "  # or: docker compose stop postgres"
    exit 1
fi

if [ ! -d "$PGDATA" ]; then
    echo "ERROR: PGDATA directory not found: $PGDATA"
    exit 1
fi

echo "=== Point-in-Time Recovery ==="
echo "  Target: ${TARGET}"
echo "  PGDATA: ${PGDATA}"
echo ""

# ── List available backups ──

echo "Available backups:"
wal-g backup-list
echo ""

# ── Confirm ──

echo "WARNING: This will REPLACE the current database cluster at ${PGDATA}."
BACKUP_DIR="${PGDATA}.old.$(date +%Y%m%d%H%M%S)"
echo "The existing data directory will be moved to ${BACKUP_DIR}"
read -p "Type 'yes' to continue: " CONFIRM
if [ "$CONFIRM" != "yes" ]; then
    echo "Aborted."
    exit 1
fi

# ── Move existing data directory ──

echo "Moving existing PGDATA to ${BACKUP_DIR}..."
mv "$PGDATA" "$BACKUP_DIR"

# ── Restore base backup ──

echo "Restoring latest base backup..."
wal-g backup-fetch "$PGDATA" LATEST

# ── Configure recovery target ──

# Strip any prior PITR recovery lines from postgresql.auto.conf (if it exists),
# then append the new recovery settings. This preserves ALTER SYSTEM settings.
AUTO_CONF="${PGDATA}/postgresql.auto.conf"
if [ -f "$AUTO_CONF" ]; then
    grep -v -E "^(# PITR recovery|restore_command|recovery_target|recovery_target_time|recovery_target_action)" \
        "$AUTO_CONF" > "${AUTO_CONF}.tmp" || true
    mv "${AUTO_CONF}.tmp" "$AUTO_CONF"
fi

if [ "$TARGET" = "latest" ]; then
    echo "Configuring recovery to latest available WAL..."
    cat >> "$AUTO_CONF" <<EOF
# PITR recovery configuration — auto-generated by restore.sh
restore_command = 'envdir /etc/wal-g/env wal-g wal-fetch %f %p'
recovery_target = 'immediate'
recovery_target_action = 'promote'
EOF
else
    echo "Configuring recovery to target time: ${TARGET}..."
    cat >> "$AUTO_CONF" <<EOF
# PITR recovery configuration — auto-generated by restore.sh
restore_command = 'envdir /etc/wal-g/env wal-g wal-fetch %f %p'
recovery_target_time = '${TARGET}'
recovery_target_action = 'promote'
EOF
fi

# Signal PostgreSQL to enter recovery mode
touch "${PGDATA}/recovery.signal"

echo ""
echo "=== Restore prepared ==="
echo ""
echo "Next steps:"
echo "  1. Start PostgreSQL:"
echo "     systemctl start postgresql"
echo "     # or: docker compose start postgres"
echo ""
echo "  2. PostgreSQL will replay WAL segments until the target time."
echo "     Monitor progress in the PostgreSQL log."
echo ""
echo "  3. Verify recovery:"
echo "     psql -c 'SELECT pg_is_in_recovery();'  -- should be 'f' after promote"
echo "     psql -c 'SELECT NOW();'                 -- sanity check"
echo ""
echo "  4. After verification, re-enable WAL archiving:"
echo "     ./enable-wal-archiving.sh"
echo ""
echo "  5. Take a fresh base backup:"
echo "     ./backup.sh"
echo ""
echo "  6. The old data directory is at: ${BACKUP_DIR}"
echo "     Remove it after confirming the restore is good:"
echo "     rm -rf ${BACKUP_DIR}"
