"""Typed access to the `datasets.config.teacher` provenance block.

Shape (mirrored by the Rust teacher module — keep in sync):
    {"host": str, "model": str, "policy": str, "cot": bool, "generated_at": str}

The block records which model wrote a dataset's training examples. It never
contains credentials. It is write-once: a dataset generated by one teacher
must not be relabeled as another's.
"""

from urllib.parse import urlsplit

from src.teacher.client import TeacherConfig


def teacher_host(api_base_url: str) -> str:
    """Displayable host of a teacher endpoint (no scheme, path, or userinfo)."""
    host = urlsplit(api_base_url).hostname
    return host or api_base_url


def build_provenance(config: TeacherConfig, generated_at: str) -> dict:
    return {
        "host": teacher_host(config.api_base_url),
        "model": config.model,
        "policy": config.policy,
        "cot": config.include_cot,
        "generated_at": generated_at,
    }


def read_provenance(dataset_config: dict | None) -> dict | None:
    """Return the teacher provenance block, or None when the dataset has none."""
    if not isinstance(dataset_config, dict):
        return None
    block = dataset_config.get("teacher")
    if not isinstance(block, dict):
        return None
    if not block.get("host") or not block.get("model"):
        return None
    return block
