import type {
  ProjectResponse,
  DocumentResponse,
  DatasetResponse,
  TrainingJobResponse,
  ModelResponse,
  EvaluationResponse,
  CreateProjectRequest,
  CreateTrainingJobRequest,
  CreateEvaluationRequest,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
  ApiKeyResponse,
  CostEstimateResponse,
  DeploymentStatusResponse,
  UploadResponse,
  ProjectPipelineStatus,
  TriggerParseResponse,
  TriggerRefineResponse,
  PaginatedResponse,
  LlmSettingsResponse,
  LlmTestResponse,
  UpdateLlmSettingsRequest,
  AdminConfigResponse,
  UpdateAdminConfigRequest,
  InferenceInstanceResponse,
  CreateInferenceInstanceRequest,
  UpdateInferenceInstanceLifecycleRequest,
  DataGuideResponse,
  CreateDataGuideRequest,
  GenerateFacetsRequest,
  UpdateFacetsRequest,
  GeneratePreviewRequest,
  RateSamplesRequest,
  UpdateGuidanceRequest,
  CatalogResponse,
} from "./generated";

// ── Re-export generated types with frontend-friendly aliases ──
// All types below are auto-generated from Rust DTOs via ts-rs.
// Run `cargo test --workspace` to regenerate.

export type {
  // Enums
  ProjectStatus,
  DocumentStatus,
  DatasetStatus,
  TrainingJobStatus,
  TrainingMethod,
  TrainingMode,
  EvaluationStatus,
  DeploymentStatus,
  // Typed structs
  EvaluationScores,
  Hyperparams,
  TrainingMetrics,
  // Response types (pass-through)
  ApiKeyResponse,
  CostEstimateResponse,
  CreateApiKeyResponse,
  DeploymentStatusResponse,
  UploadResponse,
  ProjectPipelineStatus,
  TriggerParseResponse,
  TriggerRefineResponse,
  PaginatedResponse,
  CatalogModel,
  CatalogResponse,
} from "./generated";

// Response types with frontend-friendly aliases
export type { ProjectResponse as Project } from "./generated";
export type { DocumentResponse as Document } from "./generated";
export type { DatasetResponse as Dataset } from "./generated";
export type { TrainingJobResponse as TrainingJob } from "./generated";
export type { ModelResponse as Model } from "./generated";
export type { EvaluationResponse as Evaluation } from "./generated";

// Request types with frontend-friendly aliases
export type { CreateProjectRequest as CreateProjectInput } from "./generated";
export type { CreateTrainingJobRequest as CreateTrainingJobInput } from "./generated";
export type { CreateEvaluationRequest as CreateEvaluationInput } from "./generated";
export type { CreateApiKeyRequest as CreateApiKeyInput } from "./generated";

// Settings types
export type {
  LlmSettingsResponse,
  LlmTestResponse,
  UpdateLlmSettingsRequest,
  AdminConfigResponse,
  UpdateAdminConfigRequest,
} from "./generated";

// Inference instance types
export type {
  InferenceInstanceResponse,
  CreateInferenceInstanceRequest,
  UpdateInferenceInstanceLifecycleRequest,
  InferenceInstanceHealthStatus,
  InferenceInstanceLifecycleState,
} from "./generated";

// Data guide types (Data Studio guided synthetic data generation)
export type { DataGuideResponse as DataGuide } from "./generated";
export type {
  TaskType,
  DataGuideStatus,
  Facet,
  PreviewSample,
  SampleRating,
  SampleRatingItem,
  CreateDataGuideRequest,
  GenerateFacetsRequest,
  UpdateFacetsRequest,
  GeneratePreviewRequest,
  RateSamplesRequest,
  UpdateGuidanceRequest,
  GenerateDatasetRequest,
} from "./generated";

// Team types (will be auto-generated by ts-rs after `make typegen`)
export interface TeamMember {
  id: string;
  user_id: string;
  email: string;
  role: "owner" | "admin" | "member" | "viewer";
  joined_at: string;
}

export interface TeamInvitation {
  id: string;
  email: string;
  role: "owner" | "admin" | "member" | "viewer";
  status: "pending" | "accepted" | "expired" | "revoked";
  invited_by: string;
  expires_at: string;
  created_at: string;
}

// ── Pipeline types (generated after typegen) ──

export interface TriggerFullPipelineRequest {
  task_type?: string;
  base_model: string;
  training_config: Record<string, unknown>;
}

export interface TriggerFullPipelineResponse {
  workflow_id: string;
  document_count: number;
}

// ── Frontend-only types (not in Rust DTOs) ──

export interface TrainingMetricsEntry {
  step: number;
  epoch: number;
  loss: number;
  learning_rate: number;
  grad_norm: number;
  phase: string;
  timestamp: string;
}

export interface ParsedContentResponse {
  url: string;
}

export interface ExportResponse {
  id: string;
  model_id: string;
  format: string;
  quant_type: string;
  status: string;
  has_download: boolean;
  file_size_bytes: number | null;
  error: string | null;
  created_at: string;
  completed_at: string | null;
}

export interface ExportDownloadResponse {
  download_url: string;
  file_size_bytes: number | null;
  filename: string;
}

export interface InferenceUsageDay {
  date: string;
  request_count: number;
  prompt_tokens: number;
  completion_tokens: number;
  cost_usd: number;
}

// ── API client infrastructure ──

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

const DEFAULT_TIMEOUT_MS = 30_000;
const MAX_RETRIES = 3;
const BASE_BACKOFF_MS = 500;

interface ApiError {
  error: {
    code: string;
    message: string;
  };
}

export class ApiClientError extends Error {
  code: string;
  status: number;

  constructor(status: number, body: ApiError) {
    super(body.error.message);
    this.code = body.error.code;
    this.status = status;
  }
}

/**
 * Parses an error response body into the ApiError envelope.
 *
 * Not every error response is JSON: a text/plain 400 from the API, or an HTML
 * 502 from a proxy/load balancer, would make `res.json()` throw a SyntaxError
 * that masks the real HTTP error and surfaces as a confusing toast. Guard on
 * the Content-Type header — only parse JSON when the body actually is JSON —
 * and otherwise fall back to the raw text / status line. Genuine JSON error
 * envelopes keep their original shape and behavior.
 */
async function parseErrorBody(res: Response): Promise<ApiError> {
  const contentType = res.headers.get("content-type") ?? "";
  const fallbackMessage =
    res.statusText || `Request failed with status ${res.status}`;

  if (contentType.includes("application/json")) {
    try {
      const parsed = (await res.json()) as Partial<ApiError> | null;
      if (
        parsed &&
        typeof parsed === "object" &&
        parsed.error &&
        typeof parsed.error.message === "string"
      ) {
        return parsed as ApiError;
      }
    } catch {
      // Claimed to be JSON but failed to parse — fall through to status line.
    }
    return { error: { code: "http_error", message: fallbackMessage } };
  }

  // Non-JSON body (text/plain, HTML from a proxy, empty, …).
  if (contentType.includes("text/plain")) {
    try {
      const text = (await res.text()).trim();
      if (text) {
        return { error: { code: "http_error", message: text.slice(0, 500) } };
      }
    } catch {
      // Body unavailable — fall through to the status line.
    }
  }

  return { error: { code: "http_error", message: fallbackMessage } };
}

function isRetryable(error: unknown): boolean {
  if (error instanceof ApiClientError) {
    return error.status >= 500;
  }
  // Only retry on network errors (TypeError). AbortError means timeout —
  // retrying timed-out requests can cause duplicate mutations server-side.
  return error instanceof TypeError;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Wraps fetch with a timeout (via AbortController) and retry logic
 * for transient failures (network errors, 5xx responses).
 *
 * Retries up to MAX_RETRIES times with exponential backoff.
 * Non-retryable errors (4xx, known client errors) are thrown immediately.
 */
async function fetchWithRetry(
  url: string,
  init?: RequestInit,
  timeoutMs: number = DEFAULT_TIMEOUT_MS,
): Promise<Response> {
  let lastError: unknown;

  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeoutMs);

    if (init?.signal) {
      init.signal.addEventListener("abort", () => controller.abort(), {
        once: true,
      });
    }

    try {
      const res = await fetch(url, { ...init, signal: controller.signal });

      if (res.status >= 500 && attempt < MAX_RETRIES) {
        lastError = new ApiClientError(res.status, {
          error: {
            code: "server_error",
            message: `Server returned ${res.status}`,
          },
        });
        await sleep(BASE_BACKOFF_MS * 2 ** attempt);
        continue;
      }

      return res;
    } catch (error) {
      lastError = error;

      if (!isRetryable(error) || attempt >= MAX_RETRIES) {
        throw error;
      }

      await sleep(BASE_BACKOFF_MS * 2 ** attempt);
    } finally {
      clearTimeout(timeoutId);
    }
  }

  throw lastError;
}

/**
 * Typed API client for the Platform Rust backend.
 *
 * Automatically includes the Clerk session token in requests.
 * All methods return typed responses matching the Rust DTOs.
 */
async function request<T>(
  path: string,
  options?: RequestInit & { token?: string },
): Promise<T> {
  const { token, ...fetchOptions } = options || {};

  const headers: Record<string, string> = {
    ...(fetchOptions.headers as Record<string, string>),
  };

  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }

  if (fetchOptions.body && typeof fetchOptions.body === "string") {
    headers["Content-Type"] = "application/json";
  }

  // Idempotency for mutating requests: a stable key lets the backend's
  // idempotency middleware dedupe retries (fetchWithRetry may replay 5xx /
  // network failures) so a single user action never mutates state twice.
  // The key is generated once per request() call and reused across retries.
  const method = (fetchOptions.method ?? "GET").toUpperCase();
  if (
    (method === "POST" || method === "PUT" || method === "PATCH") &&
    !headers["Idempotency-Key"]
  ) {
    headers["Idempotency-Key"] = crypto.randomUUID();
  }

  const res = await fetchWithRetry(`${API_URL}${path}`, {
    ...fetchOptions,
    headers,
  });

  if (!res.ok) {
    const body = await parseErrorBody(res);
    throw new ApiClientError(res.status, body);
  }

  if (res.status === 204) {
    return undefined as T;
  }

  return res.json();
}

// ── API methods ──

async function uploadRequest(
  path: string,
  token: string,
  formData: FormData,
): Promise<UploadResponse[]> {
  const res = await fetchWithRetry(`${API_URL}${path}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Idempotency-Key": crypto.randomUUID(),
    },
    body: formData,
  });

  if (!res.ok) {
    const body = await parseErrorBody(res);
    throw new ApiClientError(res.status, body);
  }

  return res.json();
}

export const api = {
  catalog: {
    // Public endpoint — no auth token required.
    get: (taskType?: string, pairCount?: number) => {
      const qs = new URLSearchParams();
      if (taskType) qs.set("task_type", taskType);
      if (pairCount !== undefined) qs.set("pair_count", String(pairCount));
      const query = qs.toString();
      return request<CatalogResponse>(
        `/api/v1/models/catalog${query ? `?${query}` : ""}`,
      );
    },
  },

  projects: {
    list: (token: string, offset = 0, limit = 20) =>
      request<PaginatedResponse<ProjectResponse>>(
        `/api/v1/projects?offset=${offset}&limit=${limit}`,
        { token },
      ),

    get: (token: string, id: string) =>
      request<ProjectResponse>(`/api/v1/projects/${id}`, { token }),

    create: (token: string, data: CreateProjectRequest) =>
      request<ProjectResponse>("/api/v1/projects", {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    delete: (token: string, id: string) =>
      request<void>(`/api/v1/projects/${id}`, { token, method: "DELETE" }),
  },

  documents: {
    list: (token: string, projectId: string, offset = 0, limit = 50) =>
      request<PaginatedResponse<DocumentResponse>>(
        `/api/v1/projects/${projectId}/documents?offset=${offset}&limit=${limit}`,
        { token },
      ),

    get: (token: string, id: string) =>
      request<DocumentResponse>(`/api/v1/documents/${id}`, { token }),

    upload: (token: string, projectId: string, files: File[]) => {
      const formData = new FormData();
      for (const file of files) {
        formData.append("files", file);
      }
      return uploadRequest(
        `/api/v1/projects/${projectId}/documents`,
        token,
        formData,
      );
    },

    getParsed: (token: string, id: string) =>
      request<ParsedContentResponse>(`/api/v1/documents/${id}/parsed`, {
        token,
      }),
  },

  pipeline: {
    triggerParse: (token: string, projectId: string) =>
      request<TriggerParseResponse>(`/api/v1/projects/${projectId}/parse`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),

    triggerRefine: (
      token: string,
      projectId: string,
      taskType?: string,
      config?: Record<string, unknown>,
    ) =>
      request<TriggerRefineResponse>(`/api/v1/projects/${projectId}/refine`, {
        token,
        method: "POST",
        body: JSON.stringify({ task_type: taskType, config: config || {} }),
      }),

    triggerFullPipeline: (
      token: string,
      projectId: string,
      data: TriggerFullPipelineRequest,
    ) =>
      request<TriggerFullPipelineResponse>(
        `/api/v1/projects/${projectId}/full-pipeline`,
        {
          token,
          method: "POST",
          body: JSON.stringify(data),
        },
      ),

    getStatus: (token: string, projectId: string) =>
      request<ProjectPipelineStatus>(`/api/v1/projects/${projectId}/status`, {
        token,
      }),
  },

  datasets: {
    list: (token: string, projectId: string, offset = 0, limit = 20) =>
      request<PaginatedResponse<DatasetResponse>>(
        `/api/v1/projects/${projectId}/datasets?offset=${offset}&limit=${limit}`,
        { token },
      ),

    get: (token: string, id: string) =>
      request<DatasetResponse>(`/api/v1/datasets/${id}`, { token }),

    preview: (token: string, id: string, maxRows = 20) =>
      request<Record<string, unknown>[]>(
        `/api/v1/datasets/${id}/preview?max_rows=${maxRows}`,
        { token },
      ),

    approve: (token: string, id: string) =>
      request<DatasetResponse>(`/api/v1/datasets/${id}/approve`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),

    reject: (token: string, id: string) =>
      request<DatasetResponse>(`/api/v1/datasets/${id}/reject`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),
  },

  dataGuides: {
    get: (token: string, projectId: string) =>
      request<DataGuideResponse>(`/api/v1/projects/${projectId}/data-guide`, {
        token,
      }),

    create: (token: string, projectId: string, data: CreateDataGuideRequest) =>
      request<DataGuideResponse>(`/api/v1/projects/${projectId}/data-guide`, {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    generateFacets: (token: string, id: string, data: GenerateFacetsRequest) =>
      request<DataGuideResponse>(`/api/v1/data-guides/${id}/facets`, {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    updateFacets: (token: string, id: string, data: UpdateFacetsRequest) =>
      request<DataGuideResponse>(`/api/v1/data-guides/${id}/facets`, {
        token,
        method: "PUT",
        body: JSON.stringify(data),
      }),

    generatePreview: (token: string, id: string, data: GeneratePreviewRequest) =>
      request<DataGuideResponse>(`/api/v1/data-guides/${id}/preview`, {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    rate: (token: string, id: string, data: RateSamplesRequest) =>
      request<DataGuideResponse>(`/api/v1/data-guides/${id}/rate`, {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    refine: (token: string, id: string) =>
      request<DataGuideResponse>(`/api/v1/data-guides/${id}/refine`, {
        token,
        method: "POST",
      }),

    updateGuidance: (token: string, id: string, data: UpdateGuidanceRequest) =>
      request<DataGuideResponse>(`/api/v1/data-guides/${id}/guidance`, {
        token,
        method: "PUT",
        body: JSON.stringify(data),
      }),

    generate: (token: string, id: string) =>
      request<DataGuideResponse>(`/api/v1/data-guides/${id}/generate`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),
  },

  trainingJobs: {
    list: (token: string, projectId: string, offset = 0, limit = 20) =>
      request<PaginatedResponse<TrainingJobResponse>>(
        `/api/v1/projects/${projectId}/training-jobs?offset=${offset}&limit=${limit}`,
        { token },
      ),

    get: (token: string, id: string) =>
      request<TrainingJobResponse>(`/api/v1/training-jobs/${id}`, { token }),

    create: (
      token: string,
      projectId: string,
      data: CreateTrainingJobRequest,
    ) =>
      request<TrainingJobResponse>(
        `/api/v1/projects/${projectId}/training-jobs`,
        {
          token,
          method: "POST",
          body: JSON.stringify(data),
        },
      ),

    cancel: (token: string, id: string) =>
      request<TrainingJobResponse>(`/api/v1/training-jobs/${id}/cancel`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),

    approveCost: (token: string, id: string) =>
      request<TrainingJobResponse>(`/api/v1/training-jobs/${id}/approve-cost`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),

    estimate: (
      token: string,
      projectId: string,
      data: CreateTrainingJobRequest,
    ) =>
      request<CostEstimateResponse>(
        `/api/v1/projects/${projectId}/training-jobs/estimate`,
        {
          token,
          method: "POST",
          body: JSON.stringify(data),
        },
      ),

    getMetrics: (token: string, id: string) =>
      request<Record<string, unknown>>(`/api/v1/training-jobs/${id}/metrics`, {
        token,
      }),
  },

  models: {
    list: (token: string, projectId: string, offset = 0, limit = 20) =>
      request<PaginatedResponse<ModelResponse>>(
        `/api/v1/projects/${projectId}/models?offset=${offset}&limit=${limit}`,
        { token },
      ),

    get: (token: string, id: string) =>
      request<ModelResponse>(`/api/v1/models/${id}`, { token }),

    listVersions: (token: string, id: string) =>
      request<ModelResponse[]>(`/api/v1/models/${id}/versions`, { token }),

    rollback: (token: string, id: string, targetVersionId: string) =>
      request<ModelResponse>(`/api/v1/models/${id}/rollback`, {
        token,
        method: "POST",
        body: JSON.stringify({ target_version_id: targetVersionId }),
      }),
  },

  evaluations: {
    list: (token: string, modelId: string, offset = 0, limit = 20) =>
      request<PaginatedResponse<EvaluationResponse>>(
        `/api/v1/models/${modelId}/evaluations?offset=${offset}&limit=${limit}`,
        { token },
      ),

    get: (token: string, id: string) =>
      request<EvaluationResponse>(`/api/v1/evaluations/${id}`, { token }),

    create: (token: string, modelId: string, data: CreateEvaluationRequest) =>
      request<EvaluationResponse>(`/api/v1/models/${modelId}/evaluations`, {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),
  },

  apiKeys: {
    list: (token: string, modelId: string) =>
      request<ApiKeyResponse[]>(`/api/v1/models/${modelId}/api-keys`, {
        token,
      }),

    create: (token: string, modelId: string, data: CreateApiKeyRequest) =>
      request<CreateApiKeyResponse>(`/api/v1/models/${modelId}/api-keys`, {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    revoke: (token: string, id: string) =>
      request<ApiKeyResponse>(`/api/v1/api-keys/${id}/revoke`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),
  },

  exports: {
    list: (token: string, modelId: string) =>
      request<ExportResponse[]>(`/api/v1/models/${modelId}/exports`, { token }),

    create: (token: string, modelId: string, data: { quant_type?: string }) =>
      request<ExportResponse>(`/api/v1/models/${modelId}/exports`, {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    download: (token: string, exportId: string) =>
      request<ExportDownloadResponse>(`/api/v1/exports/${exportId}/download`, {
        token,
      }),
  },

  deployments: {
    deploy: (token: string, modelId: string) =>
      request<ModelResponse>(`/api/v1/models/${modelId}/deploy`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),

    undeploy: (token: string, modelId: string) =>
      request<ModelResponse>(`/api/v1/models/${modelId}/undeploy`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),

    status: (token: string, modelId: string) =>
      request<DeploymentStatusResponse>(
        `/api/v1/models/${modelId}/deployment`,
        { token },
      ),
  },

  team: {
    listMembers: (token: string) =>
      request<TeamMember[]>("/api/v1/team/members", { token }),

    listInvitations: (token: string) =>
      request<TeamInvitation[]>("/api/v1/team/invitations", { token }),

    invite: (token: string, data: { email: string; role?: string }) =>
      request<TeamInvitation>("/api/v1/team/invitations", {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    revokeInvitation: (token: string, id: string) =>
      request<TeamInvitation>(`/api/v1/team/invitations/${id}/revoke`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),

    updateRole: (token: string, userId: string, role: string) =>
      request<TeamMember>(`/api/v1/team/members/${userId}/role`, {
        token,
        method: "PUT",
        body: JSON.stringify({ role }),
      }),

    removeMember: (token: string, userId: string) =>
      request<void>(`/api/v1/team/members/${userId}`, {
        token,
        method: "DELETE",
      }),

    acceptInvitation: (token: string, inviteToken: string) =>
      request<TeamMember>(`/api/v1/invitations/${inviteToken}/accept`, {
        token,
        method: "POST",
        body: JSON.stringify({}),
      }),
  },

  billing: {
    createCheckout: (
      token: string,
      data: { plan: string; success_url: string; cancel_url: string },
    ) =>
      request<{ url: string }>("/api/v1/billing/checkout", {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    createPortal: (token: string, data: { return_url: string }) =>
      request<{ url: string }>("/api/v1/billing/portal", {
        token,
        method: "POST",
        body: JSON.stringify(data),
      }),

    getSubscription: (token: string) =>
      request<{
        id: string;
        status: string;
        plan: string;
        current_period_end: string;
      }>("/api/v1/billing/subscription", { token }),

    getLimits: (token: string) =>
      request<{
        max_projects: number;
        max_models: number;
        max_team_members: number;
        max_training_pairs: number;
        max_storage_gb: number;
      }>("/api/v1/billing/limits", { token }),
  },

  dashboard: {
    getStats: (token: string) =>
      request<{
        total_projects: number;
        total_documents: number;
        total_training_jobs: number;
        active_training_jobs: number;
        total_models: number;
        deployed_models: number;
        total_evaluations: number;
      }>("/api/v1/dashboard/stats", { token }),

    getUsage: (token: string) =>
      request<{
        total_cost_usd: number;
        total_tokens_in: number;
        total_tokens_out: number;
        total_events: number;
        cost_by_day: Array<{ date: string; cost_usd: number }>;
      }>("/api/v1/dashboard/usage", { token }),

    getActivity: (token: string) =>
      request<
        Array<{
          id: string;
          actor_id: string;
          action: string;
          resource_type: string;
          resource_id: string | null;
          created_at: string;
        }>
      >("/api/v1/dashboard/activity", { token }),

    getInferenceUsage: (token: string) =>
      request<InferenceUsageDay[]>("/api/v1/dashboard/inference-usage", {
        token,
      }),
  },

  notifications: {
    getPreferences: (token: string) =>
      request<
        Array<{
          id: string;
          channel: string;
          event_type: string;
          enabled: boolean;
          config: Record<string, unknown>;
        }>
      >("/api/v1/notifications/preferences", { token }),

    updatePreferences: (
      token: string,
      data: {
        preferences: Array<{
          channel: string;
          event_type: string;
          enabled: boolean;
          config?: Record<string, unknown>;
        }>;
      },
    ) =>
      request<
        Array<{
          id: string;
          channel: string;
          event_type: string;
          enabled: boolean;
          config: Record<string, unknown>;
        }>
      >("/api/v1/notifications/preferences", {
        token,
        method: "PUT",
        body: JSON.stringify(data),
      }),

    getDeliveries: (token: string, offset = 0, limit = 20) =>
      request<
        PaginatedResponse<{
          id: string;
          event_type: string;
          channel: string;
          status: string;
          attempts: number;
          last_error: string | null;
          created_at: string;
          sent_at: string | null;
        }>
      >(`/api/v1/notifications/deliveries?offset=${offset}&limit=${limit}`, {
        token,
      }),

    testWebhook: (token: string, preferenceId: string) =>
      request<{
        id: string;
        event_type: string;
        channel: string;
        status: string;
        attempts: number;
        last_error: string | null;
        created_at: string;
        sent_at: string | null;
      }>(`/api/v1/notifications/preferences/${preferenceId}/test`, {
        token,
        method: "POST",
      }),

    retryDelivery: (token: string, deliveryId: string) =>
      request<{
        id: string;
        event_type: string;
        channel: string;
        status: string;
        attempts: number;
        last_error: string | null;
        created_at: string;
        sent_at: string | null;
      }>(`/api/v1/notifications/deliveries/${deliveryId}/retry`, {
        token,
        method: "POST",
      }),

    getInApp: (token: string) =>
      request<{
        items: Array<{
          id: string;
          event_type: string;
          payload: Record<string, unknown>;
          created_at: string;
          read_at: string | null;
        }>;
        unread_count: number;
      }>("/api/v1/notifications/in-app", { token }),

    markInAppRead: (token: string, id: string) =>
      request<void>(`/api/v1/notifications/in-app/${id}/read`, {
        token,
        method: "POST",
      }),

    markAllInAppRead: (token: string) =>
      request<void>("/api/v1/notifications/in-app/read-all", {
        token,
        method: "POST",
      }),
  },

  settings: {
    getLlm: (token: string) =>
      request<LlmSettingsResponse>("/api/v1/settings/llm", { token }),

    testLlm: (token: string) =>
      request<LlmTestResponse>("/api/v1/settings/llm/test", {
        token,
        method: "POST",
      }),

    updateLlm: (token: string, data: UpdateLlmSettingsRequest) =>
      request<LlmSettingsResponse>("/api/v1/settings/llm", {
        token,
        method: "PUT",
        body: JSON.stringify(data),
      }),

    deleteLlm: (token: string) =>
      request<void>("/api/v1/settings/llm", { token, method: "DELETE" }),

    getAdminConfig: (token: string) =>
      request<AdminConfigResponse>("/api/v1/settings/admin", { token }),

    updateAdminConfig: (token: string, data: UpdateAdminConfigRequest) =>
      request<AdminConfigResponse>("/api/v1/settings/admin", {
        token,
        method: "PUT",
        body: JSON.stringify(data),
      }),

    resetAdminConfig: (token: string) =>
      request<void>("/api/v1/settings/admin", { token, method: "DELETE" }),
  },

  inferenceInstances: {
    list: (token: string) =>
      request<InferenceInstanceResponse[]>(
        "/api/v1/admin/inference-instances",
        { token },
      ),

    register: (token: string, data: CreateInferenceInstanceRequest) =>
      request<InferenceInstanceResponse>(
        "/api/v1/admin/inference-instances",
        { token, method: "POST", body: JSON.stringify(data) },
      ),

    updateLifecycle: (
      token: string,
      id: string,
      data: UpdateInferenceInstanceLifecycleRequest,
    ) =>
      request<InferenceInstanceResponse>(
        `/api/v1/admin/inference-instances/${id}/lifecycle`,
        { token, method: "PATCH", body: JSON.stringify(data) },
      ),

    delete: (token: string, id: string) =>
      request<{ deleted: boolean }>(
        `/api/v1/admin/inference-instances/${id}`,
        { token, method: "DELETE" },
      ),
  },

  auditLogs: {
    list: (
      token: string,
      params: {
        offset?: number;
        limit?: number;
        action?: string;
        resource_type?: string;
      } = {},
    ) => {
      const qs = new URLSearchParams();
      if (params.offset) qs.set("offset", String(params.offset));
      if (params.limit) qs.set("limit", String(params.limit));
      if (params.action) qs.set("action", params.action);
      if (params.resource_type) qs.set("resource_type", params.resource_type);
      const query = qs.toString();
      return request<
        PaginatedResponse<{
          id: string;
          actor_id: string;
          action: string;
          resource_type: string;
          resource_id: string | null;
          metadata: Record<string, unknown>;
          created_at: string;
        }>
      >(`/api/v1/audit-logs${query ? `?${query}` : ""}`, { token });
    },
  },
};
